#!/bin/sh

git add -A 
echo "+==============================================================+"
printf "\n"
git status
echo "+==============================================================+"
sleep 1

printf "comment: "
read message
git commit -m "$message"

printf "branch: "
read branch
git push -u origin $branch
